
[review]
title = "POCLANOS ─ Review"
url = "https://poclanos.com/articles/"
entrySelector = "div.article-container div.article-group.review.content-current div.single-article"
titleSelector = "h2.single-title"
linkSelector = "a"
imageSelector = "a span img"
waitUntil = "networkidle"
onFail = "stale"

[interview]
title = "POCLANOS ─ Interview"
url = "https://poclanos.com/articles/"
entrySelector = "div.article-group.interview.content-current div.append-only-list div.single-article"
titleSelector = "h2.single-title"
linkSelector = "a"
imageSelector = "a span img"
waitUntil = "networkidle"
onFail = "stale"

[featured]
title = "POCLANOS ─ Featured"
url = "https://poclanos.com/articles/"
entrySelector = "div.article-group.featured div.append-only-list div.single-article"
titleSelector = "h2.single-title"
linkSelector = "a"
imageSelector = "a span img"
waitUntil = "networkidle"
onFail = "stale"

[album]
title = "POCLANOS ─ Album"
url = "https://poclanos.com/album-list/"
entrySelector = "div.album-container div[class^='album-single']"
titleSelector = "div.alb-title-gr span"
linkSelector = "a"
contentSelector = "a.album-title.album-artist"
imageSelector = "div.album-wrap img"
waitUntil = "networkidle"
onFail = "stale"

[naverpost_poclanos_interview]
title = "POCLANOS ─ 포크라노스 인터뷰"
url = "https://m.post.naver.com/my/series/detail.naver?seriesNo=477212&memberNo=24373938"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"
onFail = "stale"

[naverpost_poclanos_special]
title = "POCLANOS ─ 뮤직스페셜"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=479308&memberNo=24373938"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"
onFail = "stale"

[naverpost_poclanos_commentary]
title = "POCLANOS ─ 포크라노스 코멘터리"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=477089&memberNo=24373938"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"
onFail = "stale"

[msbsound_releases]
title = "MAGIC STRAWBERRY SOUND ─ Releases"
url = "http://www.msbsound.com/releases/"
entrySelector = "figure[class='effect-sadie']"
titleSelector = "h2[class='work-title']"
linkSelector = "div[class='table-cell'] a[class='mask-link']"
imageSelector = "img.attachment-1x1.size-1x1.wp-post-image"
contentSelector = "div[class='table-cell']  p[class='entry-meta']"
waitUntil = "networkidle"
onFail = "stale"

[vlive_msbsound]
title = "MAGIC STRAWBERRY SOUND ─ Media Board"
url = "https://www.vlive.tv/channel/FAC8D/board/3621?lang=ko"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[class^='post_area']"
imageSelector = "span[class^='covered_image']"
contentSelector = "span[class^='upload_time']"
waitUntil = "networkidle"
onFail = "stale"

[naverpost_msbsound_albumspecial]
title = "MSBSOUND ─ Album Special"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=444106&memberNo=838758"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"
onFail = "stale"

[naverpost_msbsound_behindstory]
title = "MSBSOUND ─ Behind Story"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=444107&memberNo=838758"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"
onFail = "stale"

[naverpost_bluevinyl_albumspecial]
title = "블루바이닐 ─ Album Special"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=564964&memberNo=47866274"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"
onFail = "stale"

[naverpost_bluevinyl_concertspecial]
title = "블루바이닐 ─ Concert Special"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=575491&memberNo=47866274"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"
onFail = "stale"
